#!/bin/sh

# Script used to control the minecraft server.
# If we are not running as root, re-run the script with sudo
# (this assumes that we have been added as sudoer for that file)

if [ `id -n` != "0" ]; then
  exec sudo -n /etc/minecraft/serverctl $@
fi
if [ ! -d "$2" ]; then
  echo "Invalid server"
  exit 101
fi
case $1 in
  start)
    systemctl start minecraft@$2
    ;;
  stop)
    systemctl stop minecraft@$2
    ;;
  *)
    echo "Invalid command"
    exit 102
    ;;
esac
